export default {
  arrowParens: "avoid",
  bracketSameLine: false,
  bracketSpacing: true,
  htmlWhitespaceSensitivity: "css",
  insertPragma: false,
  //   jsxSingleQuote: false,
  plugins: [],
  printWidth: 80,
  proseWrap: "always",
  quoteProps: "as-needed",
  requirePragma: false,
  semi: true,
  //   singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
};
